### ISSUE TITLE
Bad logo formatting on kiwi mobile

### ISSUE THREAD

**Issue by CoolMineman** [QuiltMC/quiltmc.org#7] opened 2021-04-21 02:08 UTC
Kiwi (chromium) browser android
![Screenshot-2021-04-20-21-03-14](https://user-images.githubusercontent.com/62723322/115486578-90f9b500-a21c-11eb-9a4b-68ca592eabbe.jpeg)

**Comment by Forkk** [comment] 2021-04-22 17:42
I can't seem to reproduce this. Is it still an issue?

**Comment by redcreeper14385** [comment] 2021-04-22 18:13
Cannot reproduce in Chrome's mobile devtools thing, I think it's been fixed.

**Comment by CoolMineman** [comment] 2021-04-22 18:19
Forgot to update this is kiwi specific

**Comment by redcreeper14385** [comment] 2021-04-22 18:21
Issue is likely with Kiwi itself then ¯\\\_(ツ)_/¯

**Comment by Forkk** [comment] 2021-04-22 19:15
Not sure what Kiwi could be doing to cause this. It should render the same as Chrome.

**Comment by gdude2002** [comment] 2021-04-22 20:46
I [can reproduce this issue in Kiwi Browser on Android](https://user-images.githubusercontent.com/204153/115782217-51190600-a3b3-11eb-8fd7-bed87cfba786.jpg), on a OnePlus 7 Pro.

However, [as others have mentioned, this can't be reproduced in Chrome](https://user-images.githubusercontent.com/204153/115782375-858cc200-a3b3-11eb-9481-29409170011d.jpg). It also [works fine for me in Firefox](https://user-images.githubusercontent.com/204153/115782576-bc62d800-a3b3-11eb-9cac-6272b3f7cf8c.jpg).

Overall, this is more likely to be an issue with Kiwi rather than anything particularly wrong with the site. This is unfortunately a problem with some niche browsers, including Chromium and Chrome forks - Vivaldi, for example, is known to have trouble with Discord's docs.

Because this appears to be a niche browser problem, I feel like it's potentially out of scope for us - does anyone have any specific ideas on what the problem is?

**Comment by gdude2002** [comment] 2021-05-03 17:19
It's been a while since the last reply to this issue, so I'll close it for now - I hope Kiwi fixes things, but it doesn't seem like there's anything we can reasonably do.

**Closed by gdude2002** 2021-05-03 17:19 UTC
